name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  bun_tests:
    name: bun tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: |
          bun i
          bun test

  bazel_bun_tests:
    name: bun tests (bazel)
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "25"
      # https://github.com/bazel-contrib/setup-bazel
      - uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86 # v0.19.0
        with:
          bazelisk-cache: true
          repository-cache: true
      - run: |
          bun i
          bun run build:compiler
          bun test
